name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.2'

    - name: Build Go application
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o go-commit-${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: ./go-commit-*
